# CMake script to recursively copy import dependencies
# -----------------------------------------------------------------------------
function(_copy_dependency dep)
	# Do this matching to preserve directory structure after globbing
	foreach(libdir ${LIBDIRS})
		get_filename_component(libdir "${libdir}" ABSOLUTE)
		get_filename_component(bindir "${BIN}" DIRECTORY)
		if (libdir STREQUAL bindir)
			continue()
		endif()
		string(REGEX MATCH "${libdir}.*" found ${dep})
		if (found)
			string(REPLACE "${libdir}/" "" fname "${dep}")
			get_filename_component(dname "${fname}" DIRECTORY)
			get_filename_component(dep_base "${dep}" DIRECTORY)
			get_filename_component(dep_name "${dep}" NAME)
			# Copy the library - check for the blabla/Release/hello.dll, blabla/Debug/hello.dll naming style
			if (libdir MATCHES ".*Release")
				get_filename_component(dep_debug "${dep_base}/../Debug/${dep_name}" ABSOLUTE)
				get_filename_component(tar_debug "${OUTLIBDIR}/../Debug" ABSOLUTE)
				get_filename_component(tar_release "${OUTLIBDIR}/../Release" ABSOLUTE)
				get_filename_component(tar_releasewdb "${OUTLIBDIR}/../RelWithDebInfo" ABSOLUTE)
				execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory "${tar_debug}/${dname}")
				execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory "${tar_release}/${dname}")
				execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory "${tar_releasewdb}/${dname}")
				message(STATUS "Copying ${dep_debug} to ${tar_debug}/${dname}, ${dep} to ${tar_release}/${dname} and ${dep} to ${tar_releasewdb}/${dname} ")
				execute_process(COMMAND ${CMAKE_COMMAND} -E copy "${dep_debug}" "${tar_debug}/${dname}")	
				execute_process(COMMAND ${CMAKE_COMMAND} -E copy "${dep}" "${tar_release}/${dname}")
				execute_process(COMMAND ${CMAKE_COMMAND} -E copy "${dep}" "${tar_releasewdb}/${dname}")
			else()
				message(STATUS "Copying ${dep}")
				execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory "${OUTLIBDIR}/${dname}")
				execute_process(COMMAND ${CMAKE_COMMAND} -E copy "${dep}" "${OUTLIBDIR}/${dname}")
			endif()
			###### HACK FOR QT5 ON WINDOWS ######
			if (dep_name MATCHES "Qt5Core.dll" OR dep_name MATCHES "Qt5Cored.dll")
				execute_process(COMMAND ${CMAKE_COMMAND} -E copy_directory "${dep_base}./platforms" "${OUTLIBDIR}/platforms")
				execute_process(COMMAND ${CMAKE_COMMAND} -E copy_directory "${dep_base}./imageformats" "${OUTLIBDIR}/imageformats")
			endif()
			###### END HACK FOR QT5 ON WINDOWS ######
			break()
		endif()
	endforeach()
endfunction()
# -----------------------------------------------------------------------------
function(_recursive_setup_dep_list target)
	execute_process(COMMAND "${dumpBinExe}" /DEPENDENTS /OUT:${tmp_file} "${target}")
	get_filename_component(target_nodir ${target} NAME)
	file(READ ${tmp_file} dumpedBin)
	file(REMOVE ${tmp_file})
	string(REGEX MATCH "Image has the following dependencies:.*Summary" dumpedBin ${dumpedBin})
	if(NOT dumpedBin)
		return()
	endif()
	string(REGEX MATCHALL "[^ ]*\\.dll" dependencies ${dumpedBin})
	foreach(dep ${dependencies})
		foreach(lib ${importLibs})
			string(TOUPPER ${dep} dep_upper)
			string(TOUPPER ${lib} lib_upper)
			string(REGEX MATCH ".*${dep_upper}" found ${lib_upper})
			if(found)
				if(libs_to_copy)
					list(FIND libs_to_copy ${lib} already_copied)
					if(already_copied EQUAL -1)
						set(libs_to_copy ${libs_to_copy} ${lib})
						_recursive_setup_dep_list(${lib})
					endif()
				else()
					set(libs_to_copy ${lib})
					_recursive_setup_dep_list(${lib})
				endif()
			endif()
		endforeach()
	endforeach()
	set(libs_to_copy ${libs_to_copy} PARENT_SCOPE)
endfunction()
# -----------------------------------------------------------------------------
message(STATUS "Scanning and copying dependencies...")
if(WIN32)
	set(libExt "*.dll")
else()
	set(libExt "*.so*")
endif()

# Small hack here - add bin dir
get_filename_component(bin_dir "${BIN}" DIRECTORY)
list(APPEND LIBDIRS "${bin_dir}")

# Get a list of all the libs which are acceptable to import (from argument LIBDIRS)
foreach(libdir ${LIBDIRS})
	get_filename_component(libdir_abs "${libdir}" ABSOLUTE)
	file(GLOB_RECURSE files "${libdir_abs}/${libExt}")
	list(APPEND importLibs ${files})
endforeach()

if(WIN32)
	# Find dumpbin.exe on the system
	if(MSVC_VERSION EQUAL 1800)
		set(toolsDir $ENV{VS120COMNTOOLS})
	elseif(MSVC_VERSION EQUAL 1900)
		set(toolsDir $ENV{VS140COMNTOOLS})
	else()
		message(FATAL_ERROR "VS Tools directory not found because MSVC_VERSION was not found: ${MSVC_VERSION}")
	endif()
	# Dumpbin found - now recursively search for deps
	if(EXISTS "${toolsDir}../../VC/bin/dumpbin.exe")
		get_filename_component(dumpBinExe "${toolsDir}../../VC/bin/dumpbin.exe" ABSOLUTE)
		set(tmp_file "svs_dumped_bin.txt")
		_recursive_setup_dep_list(${BIN}) # Sets libs_to_copy variable in this scope
	else()
		message(FATAL_ERROR "Could not find dumpbin.exe! Looked in ${toolsDir}../../VC/bin/dumpbin.exe")
	endif()
else()
	# Run LDD - it already does a recursive search for deps so this is a bit easier
	if(LDD_CMD STREQUAL "ldd")
		execute_process(COMMAND "${LDD_CMD}" "${BIN}" OUTPUT_VARIABLE ldd_output)
	else()
		# Need to make sure we have access to LDD
		if(EXISTS "/usr/bin/${LDD_CMD}")
			message(STATUS "LDD script found...")
		else()
			message(STATUS "LDD script not found! Copying now... sudo authentication is required...")
			execute_process(COMMAND sudo cp ${IMPORTS_DIR}/toolchains/xldd.sh /usr/bin/${LDD_CMD})
		endif()
		execute_process(COMMAND "${LDD_CMD}" --root / "${BIN}" OUTPUT_VARIABLE ldd_output)
	endif()
	if("${ldd_output}" STREQUAL "")
        message(FATAL_ERROR "No results from ldd")
	endif()
	#Split into lines for each lib
	STRING(REGEX REPLACE ";" "\\\\;" ldd_output "${ldd_output}")
	STRING(REGEX REPLACE "\n" ";" ldd_output "${ldd_output}")
	# Make the directory for libs in Linux
	execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory "${OUTLIBDIR}")
	# Check whether ldd output are copyable libs
	foreach(libline ${ldd_output})
		STRING(REGEX MATCH "(\\/[^ ]*)+" libpath ${libline})
		STRING(REGEX MATCH "[^ ]*\\.so[^ ]*" libfile ${libline})
		if(libpath)
			get_filename_component(libpath ${libpath} ABSOLUTE)
			list(FIND importLibs ${libpath} found)
			if(NOT found EQUAL -1)
				list(APPEND libs_to_copy ${libpath})
				## QT5 hack ##  TODO - make this work
				# if(${libfile} STREQUAL "libqxcb.so")
				# 	list(APPEND libs_to_copy ${libpath})
				# endif()
				## END QT5 hack ##
			endif()
		endif()
	endforeach(libline)
endif()

# Do the actual copying
foreach(lib ${libs_to_copy})
	_copy_dependency(${lib})
endforeach(lib)

# if (UNIX)
# ############# Qt5 hack ################# - TODO - make this work
# 	# Move lib/platforms to bin/ - that's where Qt will look for it
# 	if(EXISTS "${OUTLIBDIR}/platforms/libqxcb.so")
# 		get_filename_component(bin_dir "${BIN}" DIRECTORY)
# 		if(EXISTS "${bin_dir}/platforms") # Remove if it already exists
# 			file(REMOVE_RECURSE "${bin_dir}/platforms")
# 		endif()
# 		file(RENAME "${LIB}/platforms" "${bin_dir}/platforms")
# 		# Qt5 DBus is required by libqxcb that is not listed by ldd
# 		list(APPEND usedlibs "libQt5DBus.so.5")
# 	endif()
# ########## End of Qt5 hack ##############
# endif()
